import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout/layout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>personal blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          home page
        </div>
      </Layout>
    </div>
  )
}

export default Home
