import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout/layout';
import Button from '@mui/material/Button';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>personal blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          home page
          <Button>hello</Button>
          <Link href="/article/edit">
            <a>edit</a>
          </Link>
        </div>
      </Layout>
    </div>
  )
}

export default Home
